export enum ErrorCode {
  // System / Runtime
  INTERNAL_ERROR = "INTERNAL_ERROR", // 500
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE", // 503
  TIMEOUT = "TIMEOUT", // 504

  // Validation / Input
  VALIDATION_ERROR = "VALIDATION_ERROR", // 400
  INVALID_PAYLOAD = "INVALID_PAYLOAD", // 400
  MISSING_PARAMETER = "MISSING_PARAMETER", // 400
  INVALID_FORMAT = "INVALID_FORMAT", // 400

  // Authentication
  UNAUTHENTICATED = "UNAUTHENTICATED", // 401
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS", // 401
  TOKEN_EXPIRED = "TOKEN_EXPIRED", // 401
  TOKEN_INVALID = "TOKEN_INVALID", // 401

  // Authorization
  FORBIDDEN = "FORBIDDEN", // 403
  ACCESS_DENIED = "ACCESS_DENIED", // 403

  // Resource / Domain
  NOT_FOUND = "NOT_FOUND", // 404
  USER_NOT_FOUND = "USER_NOT_FOUND", // 404
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND", // 404

  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS", // 409
  RESOURCE_CONFLICT = "RESOURCE_CONFLICT", // 409

  // Database
  DB_ERROR = "DB_ERROR", // 500
  DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED", // 503
  UNIQUE_CONSTRAINT_VIOLATION = "UNIQUE_CONSTRAINT_VIOLATION", // 409
  FOREIGN_KEY_VIOLATION = "FOREIGN_KEY_VIOLATION", // 400
}

export enum HttpStatus {
  BAD_REQUEST = 400,       
  UNAUTHORIZED = 401,       
  FORBIDDEN = 403,        
  NOT_FOUND = 404,        
  CONFLICT = 409,           

  INTERNAL_SERVER_ERROR = 500, 
  SERVICE_UNAVAILABLE = 503,
  TIMEOUT = 504,
}